"""Native DOCX parser: python-docx Document → PaperContents.

Heading levels come directly from Word styles (``Title``,
``Heading 1``-``Heading 6``), giving a faithful multi-level hierarchy at
parse time. This depth is intentionally **not** preserved in the final
output: the shared post-parse stage runs ``assign_hierarchy_from_top_level``
(``pipeline/stages/post_parse.py``), which canonicalizes every *unnumbered*
heading to the IMRaD 1-2 level shape — the same structure the PDF path
produces — so DOCX and PDF outputs stay uniform. Only numbered headings
("2.3.1 …") keep deeper levels. See
docs/superpowers/specs/2026-06-15-docx-hierarchy-flattening-issue.md.

Mirrors :class:`bibr.structure.pdf_parser.PDFParser`'s public surface
(``parse``, ``_deferred_texts``, ``apply_segmentation``,
``create_content_sections``) so the existing pipeline orchestrator can
dispatch on file type without further branching.
"""

from __future__ import annotations

import base64
import io
import logging
import re
from dataclasses import dataclass

import pandas as pd

from bibr.input.docx_footnotes import load_endnotes as _load_endnotes
from bibr.input.docx_footnotes import load_footnotes as _load_footnotes
from bibr.input.docx_omml import omml_to_text as _omml_to_text
from bibr.paper_contents import (
    CanonicalSection,
    PaperContents,
    PaperFigure,
    PaperFigurePart,
    PaperSection,
    PaperSentence,
    PaperTable,
    PaperTablePart,
    PaperURLLink,
    PaperXref,
)
from bibr.structure.assembler import DeferredText, DocumentAssembler
from bibr.structure.float_labels import FIGURE_WORD, SUPPLEMENT_WORD, TABLE_WORD, caption_label
from bibr.structure.section_tree import infer_level_from_numbering
from bibr.structure.xref_utils import URL_RE, detect_xrefs
from bibr.utils.text import clean_extracted_url

logger = logging.getLogger(__name__)

# A caption paragraph that opens with a figure or table word, labelled or not.
_FIGURE_CAPTION_START_RE = re.compile(
    rf"{SUPPLEMENT_WORD}?{FIGURE_WORD}(?![A-Za-z])", re.IGNORECASE
)
_TABLE_CAPTION_START_RE = re.compile(rf"{SUPPLEMENT_WORD}?{TABLE_WORD}(?![A-Za-z])", re.IGNORECASE)

# OOXML namespaces — used for XPath into paragraph trees.
_NS = {
    "w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main",
    "m": "http://schemas.openxmlformats.org/officeDocument/2006/math",
    "a": "http://schemas.openxmlformats.org/drawingml/2006/main",
    "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
    "wp": "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing",
}

# Run-level children that end the run of text they sit in without carrying any
# text of their own: an explicit line/page/column break, a tab, and the legacy
# carriage return. Concatenating around them fuses the words on either side.
_RUN_SEPARATORS: frozenset[str] = frozenset(
    {
        f"{{{_NS['w']}}}br",
        f"{{{_NS['w']}}}tab",
        f"{{{_NS['w']}}}cr",
    }
)

_HEADING_STYLE_LEVELS: dict[str, int] = {
    "Title": 1,
    "Heading 1": 1,
    "Heading 2": 2,
    "Heading 3": 3,
    "Heading 4": 4,
    "Heading 5": 5,
    "Heading 6": 6,
    # python-docx normalises some style names — accept both spellings
    "heading 1": 1,
    "heading 2": 2,
    "heading 3": 3,
    "heading 4": 4,
    "heading 5": 5,
    "heading 6": 6,
}


@dataclass
class _Block:
    """A document block — either a paragraph or a table."""

    kind: str  # "paragraph" | "table"
    obj: object  # Paragraph or Table


def _iter_blocks(doc) -> list[_Block]:
    """Yield body paragraphs, tables, and block-level OMML in document order."""
    from docx.oxml.table import CT_Tbl
    from docx.oxml.text.paragraph import CT_P
    from docx.table import Table
    from docx.text.paragraph import Paragraph

    out: list[_Block] = []

    def walk(parent) -> None:
        for child in parent.iterchildren():
            if isinstance(child, CT_P):
                out.append(_Block(kind="paragraph", obj=Paragraph(child, doc)))
            elif isinstance(child, CT_Tbl):
                out.append(_Block(kind="table", obj=Table(child, doc)))
            elif child.tag == f"{{{_NS['m']}}}oMathPara":
                out.append(_Block(kind="math_para", obj=child))
            elif child.tag == f"{{{_NS['w']}}}sdt":
                # Structured document tag (content control). Word wraps whole
                # blocks in these — cover pages, abstract boxes, citation
                # fields, entire bibliographies generated by its reference
                # manager. Only the body's direct children were walked, so
                # every paragraph inside one was invisible to the parse. The
                # payload lives under ``w:sdtContent``; the surrounding
                # ``w:sdtPr`` properties carry no document text.
                for sdt_child in child.iterchildren():
                    if sdt_child.tag == f"{{{_NS['w']}}}sdtContent":
                        walk(sdt_child)

    walk(doc.element.body)
    return out


def _heading_level_from_style(style_name: str | None) -> int | None:
    """Return depth from Word style name, or ``None`` if not a heading."""
    if not style_name:
        return None
    return _HEADING_STYLE_LEVELS.get(style_name)


def _extract_image_blobs(paragraph, doc) -> list[tuple[bytes, str]]:
    """Find inline ``<w:drawing>`` images in a paragraph; return ``(blob, ext)`` list."""
    out: list[tuple[bytes, str]] = []
    blips = paragraph._element.findall(f".//{{{_NS['w']}}}drawing//{{{_NS['a']}}}blip")
    related = doc.part.related_parts
    for blip in blips:
        rid = blip.get(f"{{{_NS['r']}}}embed")
        if rid is None:
            continue
        image_part = related.get(rid)
        if image_part is None:
            continue
        blob = getattr(image_part, "blob", None)
        if not blob:
            continue
        # python-docx ImagePart exposes .partname like "/word/media/image1.png"
        partname = str(getattr(image_part, "partname", "image"))
        ext = partname.rsplit(".", 1)[-1].lower() if "." in partname else "bin"
        out.append((blob, ext))
    return out


def _is_caption_style(style) -> bool:
    """True for Word's Caption style and styles based on it (pandoc's "Table
    Caption" and "Image Caption")."""
    for _ in range(8):  # base-style chains are short; a malformed cycle must end
        if style is None:
            return False
        if getattr(style, "name", None) == "Caption":
            return True
        style = getattr(style, "base_style", None)
    return False


def _has_picture(paragraph) -> bool:
    return bool(paragraph._element.findall(f".//{{{_NS['w']}}}drawing//{{{_NS['a']}}}blip"))


def _nearest_block(blocks: list[_Block], index: int, step: int) -> int | None:
    """Index of the nearest block before (``step=-1``) or after (``step=1``)
    *index* that is not an empty paragraph."""
    index += step
    while 0 <= index < len(blocks):
        block = blocks[index]
        if not (
            block.kind == "paragraph"
            and not (block.obj.text or "").strip()
            and not _has_picture(block.obj)
        ):
            return index
        index += step
    return None


def _is_table_caption(blocks: list[_Block], index: int) -> bool:
    """Can the block at *index*, found next to a table, be that table's caption?

    It must be a Caption-styled paragraph, without a picture of its own, that
    does not name a figure. An unlabelled one directly under a picture stays
    the picture's caption.
    """
    block = blocks[index]
    if (
        block.kind != "paragraph"
        or not _is_caption_style(getattr(block.obj, "style", None))
        or _has_picture(block.obj)
    ):
        return False
    text = (block.obj.text or "").strip()
    if not text or _FIGURE_CAPTION_START_RE.match(text):
        return False
    if _TABLE_CAPTION_START_RE.match(text):
        return True
    previous = _nearest_block(blocks, index, -1)
    return previous is None or not (
        blocks[previous].kind == "paragraph" and _has_picture(blocks[previous].obj)
    )


def _table_caption_blocks(blocks: list[_Block]) -> dict[int, int]:
    """Map each table block's index to that of its caption paragraph.

    A table's caption is the Caption-styled paragraph directly above or below
    it (empty paragraphs between are skipped). A caption between two tables
    could be either one's, so the side that the unambiguous captions of the
    document sit on is tried first — above, on a tie.
    """
    above: dict[int, int] = {}
    below: dict[int, int] = {}
    for index, block in enumerate(blocks):
        # A table without cells is dropped, and must not take its caption along.
        if block.kind != "table" or not any(row.cells for row in block.obj.rows):
            continue
        for side, step in ((above, -1), (below, 1)):
            neighbour = _nearest_block(blocks, index, step)
            if neighbour is not None and _is_table_caption(blocks, neighbour):
                side[index] = neighbour
    shared = set(above.values()) & set(below.values())
    votes_above = sum(caption not in shared for caption in above.values())
    votes_below = sum(caption not in shared for caption in below.values())
    captions: dict[int, int] = {}
    for side in (above, below) if votes_above >= votes_below else (below, above):
        for table_index, caption_index in side.items():
            if table_index not in captions and caption_index not in captions.values():
                captions[table_index] = caption_index
    return captions


class DocxParser:
    """Parses DOCX bytes directly into a :class:`PaperContents`.

    Sentence segmentation is deferred — call :meth:`apply_segmentation`
    after :meth:`parse` with externally-produced segments, identical to
    :class:`PDFParser`.
    """

    def __init__(self, docx_bytes: bytes) -> None:
        self.docx_bytes = docx_bytes
        # Deferred-text buffer + sentence-emission driver shared with PDFParser.
        # page_number is None for DOCX — pages are a render-time concept.
        self.assembler = DocumentAssembler()

        self.sections: list[PaperSection] = []
        self.sentences: list[PaperSentence] = []
        self.links: list[PaperURLLink] = []
        self.tables: list[PaperTable] = []
        self.figures: list[PaperFigure] = []
        self.detected_headers: list[str] = []
        self.detected_footers: list[str] = []
        self.layout_hints: list[tuple[str, int]] = []

        self._section_counter = 0
        self._sentence_counter = 1
        self._paragraph_counter = 0
        self._table_counter = 1
        self._figure_counter = 1
        self._current_section_id = 0
        self._detected_title: str | None = None

        # Notes: text maps from footnotes.xml / endnotes.xml + deferred
        # references for xref linking. The two id spaces are independent (both
        # start at 1), so the maps stay separate and every pending entry
        # records which kind it came from.
        self._footnotes_map: dict[str, str] = {}
        self._endnotes_map: dict[str, str] = {}
        # Each entry: (note_text, body_section_id, deferred_text_index, kind)
        self._pending_footnotes: list[tuple[str, int, int, str]] = []
        # Hyperlink captures awaiting text_id resolution at segmentation time.
        # Each entry: (url, link_text, section_id, deferred_text_index)
        self._pending_url_links: list[tuple[str, str, int, int]] = []
        # Figures awaiting a Caption-styled paragraph immediately after
        self._unfilled_caption_figures: list[PaperFigure] = []

    # ------------------------------------------------------------------
    # Public API (mirrors PDFParser)
    # ------------------------------------------------------------------

    @property
    def _deferred_texts(self) -> list[tuple[str, int | None, int, bool, bool]]:
        """Legacy 5-tuple view of the deferred-text buffer (read-only).

        The source of truth is :attr:`assembler`; this projection keeps the
        historical ``(text, page, section_id, needs_seg, is_formula)`` contract
        that tests and analysis scripts unpack.
        """
        return [
            (e.text, e.page_number, e.section_id, e.needs_segmentation, e.is_formula)
            for e in self.assembler.entries
        ]

    def parse(self) -> PaperContents:
        """Walk the DOCX body and populate sections/tables/deferred texts."""
        from docx import Document  # lazy import — keeps load cost off bibr import

        # Root section (section_id=0)
        self.sections.append(
            PaperSection(
                section_id=0,
                header="Root",
                level=0,
                parent_section_id=None,
            )
        )

        try:
            doc = Document(io.BytesIO(self.docx_bytes))
        except Exception as exc:
            from bibr.exceptions import ProcessingError

            raise ProcessingError(f"Failed to open DOCX: {exc}") from exc

        self._doc = doc  # needed by image/footnote helpers
        self._footnotes_map = _load_footnotes(doc)
        self._endnotes_map = _load_endnotes(doc)

        blocks = _iter_blocks(doc)
        # A table's caption paragraph leaves the body text, as a figure's does.
        table_captions = _table_caption_blocks(blocks)
        caption_blocks = set(table_captions.values())
        for index, block in enumerate(blocks):
            if block.kind == "paragraph":
                if index not in caption_blocks:
                    self._handle_paragraph(block.obj)
            elif block.kind == "table":
                caption_index = table_captions.get(index)
                caption = (
                    (blocks[caption_index].obj.text or "").strip()
                    if caption_index is not None
                    else None
                )
                self._handle_table(block.obj, caption=caption)
            elif block.kind == "math_para":
                self._handle_math_para(block.obj)

        return PaperContents(
            sentences=[],
            sections=self.sections,
            tables=self.tables,
            links=self.links,
            sections_text={},
            figures=self.figures,
            xrefs=[],
            detected_title=self._detected_title,
            detected_headers=self.detected_headers,
            detected_footers=self.detected_footers,
            layout_hints=self.layout_hints,
        )

    def _make_sentence(
        self,
        entry: DeferredText,
        text: str,
        text_id: int,
        paragraph_id: int,
    ) -> PaperSentence:
        """Build a DOCX sentence — no provenance/region_meta side-channels, and
        never OCR text.

        Formula entries are intentionally left with ``is_display_formula`` at
        its default of ``False`` (the historical DOCX behaviour).
        """
        return PaperSentence(
            text_id=text_id,
            text=text,
            section_id=entry.section_id,
            paragraph_id=paragraph_id,
            page_number=entry.page_number,
            from_ocr=False,
        )

    def apply_segmentation(
        self,
        contents: PaperContents,
        all_segments: list[list[str]],
    ) -> None:
        """Populate sentences from externally-segmented results.

        The shared assembler drives sentence emission (also tracking the last
        text_id per deferred entry for footnote xref linking). URL detection is
        deferred to a second pass here so hyperlink-resolved entries can guard
        against duplicate regex matches on the same text.
        """
        self.sentences, self._sentence_counter, self._paragraph_counter = self.assembler.emit(
            all_segments,
            sentence_factory=self._make_sentence,
            sentence_counter=self._sentence_counter,
            paragraph_counter=self._paragraph_counter,
        )

        # Resolve pending hyperlink captures: the deferred index points to the
        # paragraph entry; use its last emitted sentence's text_id (or the next
        # one if the entry itself produced no sentences).
        for url, link_text, sec_id, deferred_idx in self._pending_url_links:
            text_id = self._find_nearest_text_id(deferred_idx)
            link_paragraph_id: int | None = None
            for sent in self.sentences:
                if sent.text_id == text_id:
                    link_paragraph_id = sent.paragraph_id
                    break
            self.links.append(
                PaperURLLink(
                    url=url,
                    section_id=sec_id,
                    paragraph_id=link_paragraph_id if link_paragraph_id is not None else 0,
                    text_id=text_id,
                    link_text=link_text,
                )
            )

        # Second pass: regex-detect URLs in sentence text, skipping any
        # ``(url, text_id)`` pair already covered by a resolved hyperlink so
        # ``https://...`` displayed verbatim inside a ``w:hyperlink`` doesn't
        # produce a duplicate ``PaperURLLink``.
        # Limitation: ``_find_nearest_text_id`` resolves to the *last* sentence
        # of a multi-sentence paragraph, so a URL-as-display-text hyperlink in
        # an earlier sentence of the same paragraph can still produce a regex
        # duplicate. In practice the fix targets URL-only paragraphs (the
        # common case for verbatim DOI/repository links).
        hyperlink_covered = {(link.url, link.text_id) for link in self.links}
        for sent in self.sentences:
            self._detect_urls(sent, hyperlink_covered)

        contents.sentences = self.sentences
        contents.links = self.links
        contents.sections_text = DocumentAssembler.build_sections_text(self.sentences)
        contents.xrefs = detect_xrefs(self.sentences, self.tables, self.figures)

    def create_content_sections(self, contents: PaperContents) -> None:
        """Create dedicated sections for figures, tables, and footnotes.

        Mirrors :meth:`PDFParser.create_content_sections` so downstream
        post-parse logic sees the same shape.
        """
        # --- Figure sections ---
        for fig in self.figures:
            fig._body_section_id = fig.section_id
            self._section_counter += 1
            section = PaperSection(
                section_id=self._section_counter,
                header=f"Figure {fig.figure_id}",
                level=1,
                parent_section_id=0,
                section_type=CanonicalSection.FIGURE,
                synthetic_kind="figure",
            )
            contents.sections.append(section)
            fig.section_id = self._section_counter

            if fig.caption:
                self._paragraph_counter += 1
                contents.sentences.append(
                    PaperSentence(
                        text_id=self._sentence_counter,
                        text=fig.caption,
                        section_id=self._section_counter,
                        paragraph_id=self._paragraph_counter,
                        page_number=None,
                        from_ocr=False,
                    )
                )
                self._sentence_counter += 1

        # --- Table sections ---
        for tbl in self.tables:
            tbl._body_section_id = tbl.section_id
            self._section_counter += 1
            section = PaperSection(
                section_id=self._section_counter,
                header=f"Table {tbl.table_id}",
                level=1,
                parent_section_id=0,
                section_type=CanonicalSection.TABLE,
                synthetic_kind="table",
            )
            contents.sections.append(section)
            tbl.section_id = self._section_counter

            if tbl.caption:
                self._paragraph_counter += 1
                contents.sentences.append(
                    PaperSentence(
                        text_id=self._sentence_counter,
                        text=tbl.caption,
                        section_id=self._section_counter,
                        paragraph_id=self._paragraph_counter,
                        page_number=None,
                        from_ocr=False,
                    )
                )
                self._sentence_counter += 1

        # --- Footnote / endnote sections + xrefs ---
        # Word numbers footnotes and endnotes independently, so the *printed*
        # marker is each note's position within its own kind. ``xref_id`` is the
        # note's own text row (``text_id``), unique across both kinds.
        printed_counts: dict[str, int] = {}
        for fn_text, _orig_section, deferred_idx, kind in self._pending_footnotes:
            printed_counts[kind] = printed_counts.get(kind, 0) + 1
            printed_num = printed_counts[kind]
            label = "Endnote" if kind == "endnote" else "Footnote"
            self._section_counter += 1
            footnote_section_id = self._section_counter
            contents.sections.append(
                PaperSection(
                    section_id=footnote_section_id,
                    header=f"{label} {printed_num}",
                    level=1,
                    parent_section_id=0,
                    section_type=CanonicalSection.FOOTNOTE,
                    synthetic_kind="footnote",
                    footnote_label=str(printed_num),
                )
            )

            self._paragraph_counter += 1
            footnote_text_id = self._sentence_counter
            contents.sentences.append(
                PaperSentence(
                    text_id=footnote_text_id,
                    text=fn_text,
                    section_id=footnote_section_id,
                    paragraph_id=self._paragraph_counter,
                    page_number=None,
                    from_ocr=False,
                )
            )
            self._sentence_counter += 1

            nearest_text_id = self._find_nearest_text_id(deferred_idx)
            contents.xrefs.append(
                PaperXref(
                    xref_id=footnote_text_id,
                    xref_type="foot",
                    contents=str(printed_num),
                    text_id=nearest_text_id,
                )
            )

    def _find_nearest_text_id(self, deferred_idx: int) -> int:
        """Last text_id at or before ``deferred_idx`` in the deferred-texts stream."""
        last_text_id = self.assembler.last_text_id
        if not last_text_id:
            return self.sentences[0].text_id if self.sentences else 1
        clamped = min(max(0, deferred_idx), len(last_text_id) - 1)
        for i in range(clamped, -1, -1):
            tid = last_text_id[i]
            if tid is not None:
                return tid
        return self.sentences[0].text_id if self.sentences else 1

    # ------------------------------------------------------------------
    # Block handlers
    # ------------------------------------------------------------------

    def _handle_paragraph(self, paragraph) -> None:
        style_name = getattr(paragraph.style, "name", None)

        # Quick path: heading paragraphs cannot host inline math/images/refs we care about.
        plain = (paragraph.text or "").strip()
        level = _heading_level_from_style(style_name)
        if level is not None:
            if plain:
                self._handle_heading(plain, level, style_name)
            return

        # Caption-styled paragraph: drain pending images, attach text as caption.
        if self._unfilled_caption_figures and plain and _is_caption_style(paragraph.style):
            fig = self._unfilled_caption_figures.pop(0)
            fig.caption = plain
            fig.label = caption_label(plain, "figure")
            return

        # Walk the paragraph XML in document order to interleave:
        #   - w:t (text)
        #   - w:footnoteReference / w:endnoteReference (note IDs)
        #   - m:oMath (inline math → wrap in $...$)
        #   - m:oMathPara (display math → emit as separate deferred entry)
        #   - w:drawing (inline image → register as PaperFigure)
        text_buf: list[str] = []
        # (kind, id) pairs — "footnote" and "endnote" ids collide otherwise.
        pending_note_refs: list[tuple[str, str]] = []
        had_image = False
        w = _NS["w"]
        m = _NS["m"]

        def flush_body() -> None:
            txt = "".join(text_buf).strip()
            text_buf.clear()
            if not txt:
                return
            # Footnote refs collected so far attach to this just-flushed entry.
            deferred_idx = self.assembler.append(txt, None, self._current_section_id, True, False)
            for kind, note_id in pending_note_refs:
                source = self._footnotes_map if kind == "footnote" else self._endnotes_map
                note_text = source.get(note_id, "").strip()
                if note_text:
                    self._pending_footnotes.append(
                        (note_text, self._current_section_id, deferred_idx, kind)
                    )
            pending_note_refs.clear()

        def walk_run(run_el, extra_buf: list[str] | None = None) -> None:
            """Pull text/footnotes/math from a single ``w:r`` run.

            If ``extra_buf`` is provided, text emitted into ``text_buf`` is
            mirrored into it — used so a ``w:hyperlink`` wrapper can capture
            its display text without re-implementing this walk.
            """
            nonlocal had_image

            def emit_separator() -> None:
                """Space for markup that ends a run of text, if not already spaced."""
                if text_buf and text_buf[-1] and not text_buf[-1][-1].isspace():
                    text_buf.append(" ")
                    if extra_buf is not None:
                        extra_buf.append(" ")

            for run_child in run_el.iterchildren():
                rt = run_child.tag
                if rt == f"{{{w}}}t" and run_child.text:
                    text_buf.append(run_child.text)
                    if extra_buf is not None:
                        extra_buf.append(run_child.text)
                elif rt in _RUN_SEPARATORS:
                    # A line break, tab or carriage return inside a run carries
                    # no text of its own, so dropping it fused the words on
                    # either side: a Shift+Enter title page collapsed to
                    # "Cognitive load and recallJane SmithDepartment of...".
                    # Word splits runs mid-word for formatting, so only these
                    # explicit separators may contribute whitespace — adjacent
                    # <w:t> must still concatenate untouched.
                    emit_separator()
                elif rt == f"{{{w}}}footnoteReference":
                    fn_id = run_child.get(f"{{{w}}}id")
                    if fn_id is not None:
                        pending_note_refs.append(("footnote", fn_id))
                elif rt == f"{{{w}}}endnoteReference":
                    # Endnote references were dropped on the floor, so a
                    # document using endnotes (the humanities convention for
                    # bibliographies) exported none of them.
                    en_id = run_child.get(f"{{{w}}}id")
                    if en_id is not None:
                        pending_note_refs.append(("endnote", en_id))
                elif rt == f"{{{m}}}oMath":
                    inline = _omml_to_text(run_child)
                    if inline:
                        text_buf.append(f"${inline}$")
                        if extra_buf is not None:
                            extra_buf.append(f"${inline}$")
                elif rt == f"{{{w}}}drawing":
                    had_image = True
                    # A drawing can be a text box rather than a picture, and
                    # its paragraphs are real document text — pull quotes,
                    # boxed methods notes, poster-style layouts. Nothing walked
                    # into it, so that text was lost entirely.
                    for txbx in run_child.iter(f"{{{w}}}txbxContent"):
                        boxed = " ".join(
                            t.text.strip() for t in txbx.iter(f"{{{w}}}t") if t.text
                        ).strip()
                        if boxed:
                            text_buf.append(boxed)
                            if extra_buf is not None:
                                extra_buf.append(boxed)

        def walk_runs_in_wrapper(wrapper_el, into_buf: list[str] | None = None) -> None:
            """Walk ``w:r`` children of a wrapper (``w:hyperlink``, ``w:ins``).

            ``into_buf``, if provided, mirrors text from each contained run via
            ``walk_run``'s ``extra_buf`` parameter — used to capture hyperlink
            display text for ``PaperURLLink.link_text`` while still keeping the
            text inline in the paragraph stream.
            """
            for child in wrapper_el.iterchildren():
                ctag = child.tag
                if ctag == f"{{{w}}}r":
                    walk_run(child, into_buf)
                elif ctag in (f"{{{w}}}hyperlink", f"{{{w}}}ins"):
                    walk_runs_in_wrapper(child, into_buf)

        for child in paragraph._element.iterchildren():
            tag = child.tag
            if tag == f"{{{m}}}oMathPara":
                # Display math — flush any text so far, then emit math as own entry
                flush_body()
                math_text = " ".join(_omml_to_text(om) for om in child.iter(f"{{{m}}}oMath"))
                math_text = math_text.strip()
                if math_text:
                    self.assembler.append(
                        f"$${math_text}$$",
                        None,
                        self._current_section_id,
                        needs_segmentation=False,
                        is_formula=True,
                    )
            elif tag == f"{{{m}}}oMath":
                inline = _omml_to_text(child)
                if inline:
                    text_buf.append(f"${inline}$")
            elif tag == f"{{{w}}}r":
                # Run: walk for w:t, note references, m:oMath, w:drawing
                walk_run(child)
            elif tag == f"{{{w}}}hyperlink":
                # Hyperlink: capture the URL from the relationship target, then
                # walk nested runs so their text contributes to paragraph flow.
                rel_id = child.get(f"{{{_NS['r']}}}id")
                target_url: str | None = None
                if rel_id is not None:
                    rel = self._doc.part.rels.get(rel_id)
                    if rel is not None:
                        target_url = getattr(rel, "target_ref", None) or getattr(
                            rel, "target", None
                        )
                link_text_buf: list[str] = []
                walk_runs_in_wrapper(child, link_text_buf)
                if target_url:
                    link_text = "".join(link_text_buf).strip() or target_url
                    # text_id is unknown until segmentation; record the deferred
                    # entry index that *will* hold this paragraph's text. Since
                    # we have not yet flushed, the next deferred index is
                    # ``len(self._deferred_texts)`` — apply_segmentation resolves
                    # it once sentences exist.
                    self._pending_url_links.append(
                        (
                            target_url,
                            link_text,
                            self._current_section_id,
                            len(self.assembler),
                        )
                    )
            elif tag == f"{{{w}}}ins":
                # Tracked-change insertion: walk its runs as paragraph-level text.
                walk_runs_in_wrapper(child)

        # Images: extract after the text walk so we know section context
        if had_image:
            for blob, _ext in _extract_image_blobs(paragraph, self._doc):
                image_b64 = base64.b64encode(blob).decode("ascii")
                fig = PaperFigure(
                    figure_id=self._figure_counter,
                    section_id=self._current_section_id,
                    image_b64=image_b64,
                    caption=None,
                    page_number=None,
                    parts=[
                        PaperFigurePart(
                            page_number=None,
                            bbox=None,
                            image_b64=image_b64,
                        )
                    ],
                )
                self.figures.append(fig)
                self._unfilled_caption_figures.append(fig)
                self._figure_counter += 1

        flush_body()

    def _handle_heading(self, text: str, level: int, style_name: str | None) -> None:
        # Capture the document Title style (or first Heading 1) as the paper title
        if self._detected_title is None and style_name in (
            "Title",
            "Heading 1",
            "heading 1",
        ):
            self._detected_title = text

        # Deepen via numbering pattern when present (e.g. "2.3.1 Subsection" → 3)
        inferred = infer_level_from_numbering(text)
        if inferred is not None and inferred > level:
            level = inferred

        self._section_counter += 1
        parent_id = 0
        for sec in reversed(self.sections):
            if 0 < sec.level < level:
                parent_id = sec.section_id
                break

        self.sections.append(
            PaperSection(
                section_id=self._section_counter,
                header=text,
                level=level,
                parent_section_id=parent_id,
            )
        )
        self._current_section_id = self._section_counter

    def _handle_math_para(self, omath_para_el) -> None:
        """Block-level OMML — emit as a non-segmented formula deferred entry."""
        m = _NS["m"]
        math_text = " ".join(_omml_to_text(om) for om in omath_para_el.iter(f"{{{m}}}oMath"))
        math_text = math_text.strip()
        if not math_text:
            return
        self.assembler.append(
            f"$${math_text}$$",
            None,
            self._current_section_id,
            needs_segmentation=False,
            is_formula=True,
        )

    def _handle_table(self, table, *, caption: str | None = None) -> None:
        rows = list(table.rows)
        if not rows:
            return

        cell_rows = [[cell.text.strip() for cell in row.cells] for row in rows]
        # Pad ragged rows so DataFrame construction is uniform
        width = max(len(r) for r in cell_rows)
        cell_rows = [r + [""] * (width - len(r)) for r in cell_rows]

        header_row = cell_rows[0]
        data_rows = cell_rows[1:] if len(cell_rows) > 1 else []
        df = pd.DataFrame(data_rows, columns=header_row)
        if df.empty and not header_row:
            return

        html = df.to_html(index=False)
        self.tables.append(
            PaperTable(
                table_id=self._table_counter,
                df=df,
                tbl_html=html,
                section_id=self._current_section_id,
                caption=caption or None,
                page_number=None,
                parts=[
                    PaperTablePart(
                        page_number=None,
                        bbox=None,
                        tbl_html=html,
                        df=df,
                    )
                ],
                label=caption_label(caption, "table"),
            )
        )
        self._table_counter += 1

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _detect_urls(
        self,
        sent: PaperSentence,
        already_covered: set[tuple[str, int]] | None = None,
    ) -> None:
        """Match URL_RE on the sentence and append PaperURLLink entries.

        ``already_covered`` is an optional ``{(url, text_id)}`` guard set —
        regex hits whose ``(url, text_id)`` is in the set are skipped so a
        ``w:hyperlink`` whose display text equals its URL doesn't produce a
        second link entry.
        """
        for m in URL_RE.finditer(sent.text):
            url = clean_extracted_url(m.group(0))
            if already_covered is not None and (url, sent.text_id) in already_covered:
                continue
            self.links.append(
                PaperURLLink(
                    url=url,
                    section_id=sent.section_id,
                    paragraph_id=sent.paragraph_id,
                    text_id=sent.text_id,
                    link_text=None,
                )
            )
