"""Outline guard cases: records and the verdicts of the frozen guard v1 on them.

The verdicts were produced by running the guard as the popo evaluation froze it
(scripts/outline_guard.py, 2026-10-03) on these records, and are copied here as data.
Each record has the shape of one of its outline lines: ``items`` with ``title``, ``level``,
``page_no`` (1-based or None) and ``g_page``/``g_doc`` (the title is printed on its target
page +-1 / anywhere), plus ``meta_title``, ``n_pages`` and ``text_chars``.
"""

from __future__ import annotations

CASES = {
    "plain_pass": {
        "rec": {
            "items": [
                {"title": "Introduction", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Participants", "level": 2, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
                {"title": "Discussion", "level": 1, "page_no": 9, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Introduction", "Methods", "Participants", "Results", "Discussion"],
    },
    "no_outline": {
        "rec": {"items": [], "meta_title": None, "n_pages": 10, "text_chars": 5000},
        "pass": False,
        "reject": "R1_too_few",
        "dropped": [],
        "kept": [],
    },
    "two_entries": {
        "rec": {
            "items": [
                {"title": "Introduction", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": False,
        "reject": "R1_too_few",
        "dropped": [],
        "kept": ["Introduction", "Methods"],
    },
    "every_cleanup_rule": {
        "rec": {
            "items": [
                {"title": "   ", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "12", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Contents", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Figure 2", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {
                    "title": "A Long Paper Title On Outlines",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Introduction", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
            ],
            "meta_title": "A long paper title on outlines",
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [
            ["C1_blank", "   "],
            ["C2_page", "12"],
            ["C3_nav", "Contents"],
            ["C4_float", "Figure 2"],
            ["C5_title", "A Long Paper Title On Outlines"],
        ],
        "kept": ["Introduction", "Methods", "Results"],
    },
    "short_title_is_kept": {
        "rec": {
            "items": [
                {"title": "Notes", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
                {"title": "Discussion", "level": 1, "page_no": 9, "g_page": True, "g_doc": True},
            ],
            "meta_title": "Notes",
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Notes", "Methods", "Results", "Discussion"],
    },
    "wrapper": {
        "rec": {
            "items": [
                {
                    "title": "Journal Wrapper",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Introduction", "level": 2, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 2, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 2, "page_no": 6, "g_page": True, "g_doc": True},
                {"title": "Discussion", "level": 2, "page_no": 9, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [["C6_wrapper", "Journal Wrapper"]],
        "kept": ["Introduction", "Methods", "Results", "Discussion"],
    },
    "two_top_levels_are_no_wrapper": {
        "rec": {
            "items": [
                {
                    "title": "Journal Wrapper",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Introduction", "level": 2, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 2, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Journal Wrapper", "Introduction", "Methods", "Results"],
    },
    "wrapper_after_a_dropped_first_entry": {
        "rec": {
            "items": [
                {"title": "Cover", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {
                    "title": "Journal Wrapper",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Introduction", "level": 2, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 2, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 2, "page_no": 6, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [["C3_nav", "Cover"], ["C6_wrapper", "Journal Wrapper"]],
        "kept": ["Introduction", "Methods", "Results"],
    },
    "no_pages": {
        "rec": {
            "items": [
                {
                    "title": "Introduction",
                    "level": 1,
                    "page_no": None,
                    "g_page": None,
                    "g_doc": True,
                },
                {"title": "Methods", "level": 1, "page_no": None, "g_page": None, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": None, "g_page": None, "g_doc": True},
                {"title": "Discussion", "level": 1, "page_no": 9, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": False,
        "reject": "R2_targets",
        "dropped": [],
        "kept": ["Introduction", "Methods", "Results", "Discussion"],
    },
    "half_without_pages_is_no_reject": {
        "rec": {
            "items": [
                {
                    "title": "Introduction",
                    "level": 1,
                    "page_no": None,
                    "g_page": None,
                    "g_doc": True,
                },
                {"title": "Methods", "level": 1, "page_no": None, "g_page": None, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
                {"title": "Discussion", "level": 1, "page_no": 9, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Introduction", "Methods", "Results", "Discussion"],
    },
    "all_on_one_page": {
        "rec": {
            "items": [
                {"title": "Introduction", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {"title": "Discussion", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 5,
            "text_chars": 5000,
        },
        "pass": False,
        "reject": "R2_targets",
        "dropped": [],
        "kept": ["Introduction", "Methods", "Results", "Discussion"],
    },
    "all_on_one_page_of_two": {
        "rec": {
            "items": [
                {"title": "Introduction", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {"title": "Discussion", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 2,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Introduction", "Methods", "Results", "Discussion"],
    },
    "ungrounded": {
        "rec": {
            "items": [
                {"title": "Issue 1", "level": 1, "page_no": 1, "g_page": False, "g_doc": True},
                {"title": "Issue 2", "level": 1, "page_no": 3, "g_page": False, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 8, "g_page": False, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 2500,
        },
        "pass": False,
        "reject": "R3_ungrounded",
        "dropped": [],
        "kept": ["Issue 1", "Issue 2", "Methods", "Results"],
    },
    "half_grounded_passes": {
        "rec": {
            "items": [
                {"title": "Issue 1", "level": 1, "page_no": 1, "g_page": False, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
                {"title": "Issue 2", "level": 1, "page_no": 8, "g_page": False, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 2500,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Issue 1", "Methods", "Results", "Issue 2"],
    },
    "ungrounded_below_the_text_gate": {
        "rec": {
            "items": [
                {"title": "Issue 1", "level": 1, "page_no": 1, "g_page": False, "g_doc": True},
                {"title": "Issue 2", "level": 1, "page_no": 3, "g_page": False, "g_doc": True},
                {"title": "Issue 3", "level": 1, "page_no": 6, "g_page": False, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 1999,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Issue 1", "Issue 2", "Issue 3"],
    },
    "ungrounded_at_the_text_gate": {
        "rec": {
            "items": [
                {"title": "Issue 1", "level": 1, "page_no": 1, "g_page": False, "g_doc": True},
                {"title": "Issue 2", "level": 1, "page_no": 3, "g_page": False, "g_doc": True},
                {"title": "Issue 3", "level": 1, "page_no": 6, "g_page": False, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 2000,
        },
        "pass": False,
        "reject": "R3_ungrounded",
        "dropped": [],
        "kept": ["Issue 1", "Issue 2", "Issue 3"],
    },
    "no_page_entries_are_grounded_anywhere": {
        "rec": {
            "items": [
                {"title": "Issue 1", "level": 1, "page_no": None, "g_page": None, "g_doc": False},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": None, "g_page": None, "g_doc": True},
                {"title": "Discussion", "level": 1, "page_no": 9, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 3000,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Issue 1", "Methods", "Results", "Discussion"],
    },
    "nav_names": {
        "rec": {
            "items": [
                {
                    "title": "Table of Contents",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {
                    "title": "Microsoft Word - draft.docx",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Cover Page", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "full-text", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {
                    "title": "manuscript.PDF",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Introduction", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [
            ["C3_nav", "Table of Contents"],
            ["C3_nav", "Microsoft Word - draft.docx"],
            ["C3_nav", "Cover Page"],
            ["C3_nav", "full-text"],
            ["C3_nav", "manuscript.PDF"],
        ],
        "kept": ["Introduction", "Methods", "Results"],
    },
    "float_names": {
        "rec": {
            "items": [
                {
                    "title": "Supplementary Table 1",
                    "level": 1,
                    "page_no": 1,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Fig. 3a", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Scheme 2", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Box 2", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Figures 1", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {
                    "title": "Table of Results",
                    "level": 1,
                    "page_no": 3,
                    "g_page": True,
                    "g_doc": True,
                },
                {"title": "Introduction", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [
            ["C4_float", "Supplementary Table 1"],
            ["C4_float", "Fig. 3a"],
            ["C4_float", "Scheme 2"],
            ["C4_float", "Box 2"],
            ["C4_float", "Figures 1"],
        ],
        "kept": ["Table of Results", "Introduction", "Methods"],
    },
    "page_labels": {
        "rec": {
            "items": [
                {"title": "12", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "iv", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Page 3", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "p. 3", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "3 of 10", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Seite 4", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "xiv", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "12-14", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "mix", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Vivid", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Mid-1990s", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Introduction", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "Methods", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Results", "level": 1, "page_no": 6, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [
            ["C2_page", "12"],
            ["C2_page", "iv"],
            ["C2_page", "Page 3"],
            ["C2_page", "p. 3"],
            ["C2_page", "3 of 10"],
            ["C2_page", "Seite 4"],
            ["C2_page", "xiv"],
            ["C2_page", "12-14"],
            ["C2_page", "mix"],
        ],
        "kept": ["Vivid", "Mid-1990s", "Introduction", "Methods", "Results"],
    },
    "unicode_titles": {
        "rec": {
            "items": [
                {"title": "Résumé ①", "level": 1, "page_no": 1, "g_page": True, "g_doc": True},
                {"title": "ﬁnal ﬁndings", "level": 1, "page_no": 2, "g_page": True, "g_doc": True},
                {"title": "Straße", "level": 1, "page_no": 3, "g_page": True, "g_doc": True},
                {"title": "Ångström", "level": 1, "page_no": 4, "g_page": True, "g_doc": True},
            ],
            "meta_title": None,
            "n_pages": 10,
            "text_chars": 5000,
        },
        "pass": True,
        "reject": None,
        "dropped": [],
        "kept": ["Résumé ①", "ﬁnal ﬁndings", "Straße", "Ångström"],
    },
}
